### ISSUE TITLE
Properly rehydrate default slot content

### ISSUE THREAD

**Issue by treshugart** [skatejs/ssr#10]
We currently render the entire composed tree for search engines. However, we are only rehydrating shadow roots and their slots. We aren't taking the content composed into slots and moving them back into the host as light DOM if it's composed content (not default content).

- [ ] How are named slots handled?
- [ ] Keep slot content if it's the default content (might need a temporary `default` flag on the slot.
- [ ] Is there a use case for more than two levels of slots (`<slot><slot><slot>...`)? If so, need to figure this out.

**Comment by bedeoverend** [comment]
I'm confused - I thought we were covering rehydration of composed back into light DOM?

So in the nametag example, the rehydrated content has been pulled out of the composed slots and put it back into the light DOM. That addresses point 3 at least (and I think it should still work with point 4 too - i.e. n-nested slots, though haven't tested that) - unless I'm misunderstanding the issues?

**Comment by treshugart** [comment]
I think I'm the one who was confused. I can't remember exactly why I put that there so I've removed it. For the last one, I just want to test it and if it works, then awesome.
