### ISSUE TITLE
Rehydration still broken with polyfills

### ISSUE THREAD

**Issue by treshugart** [skatejs/ssr#13]
The rehydration seems to "work", as in there's no errors, but things look horrible, like styles never got encapsulated. It'd be nice if we can find some way to easily work with the polyfills so consumers don't have to think about it.

It seems Googlebot still indexes content properly:

<img width="645" alt="screen shot 2017-07-29 at 3 18 03 pm" src="https://user-images.githubusercontent.com/136556/28742401-bed3273a-7472-11e7-9b46-e9027a6b56d3.png">

But it looks like crap:

<img width="1118" alt="screen shot 2017-07-29 at 3 30 28 pm" src="https://user-images.githubusercontent.com/136556/28742406-f9528040-7472-11e7-8ae5-94554b4b6961.png">

**Comment by bedeoverend** [comment]
So imperatively calling ShadyCSS `prepareTemplate` methods and such seem to fix this, _but_ as [mentioned](https://github.com/webcomponents/shadycss/issues/19#issuecomment-297165227) in https://github.com/webcomponents/shadycss/issues/19, we've got problem that ShadyCSS assumes a custom element definition has one set of styles, and similar problem meaning no support for non-custom elements.

Given these limitations of ShadyCSS, should we add support with these known caveats, then iterate, or just keep looking for an alternative solution? My gut says the former, but given how unintuitive and frustrating the bugs are, I'm not so sure...

**Comment by treshugart** [comment]
I like the idea of trying something like this, in this order:

1. Opt for css-in-js for encapsulation
2. Dedupe styles in the head before rehydration
3. Bring in styles from the head during rehydration
4. Start looking at possible ways to not have to use css-in-js
