### ISSUE TITLE
Add option to return the rendered custom element with a populated light dom

### ISSUE THREAD

**Issue by mortenson** [skatejs/ssr#23]
Hi there! I'm totally new to web components so I'd ask you to excuse any misunderstandings I may have about this package. 🙇

A requirement for a project I'm working on is that the light dom of custom elements is populated by the SSR implementation. This hypothetically enables static-text-crawlers to index my site based on its text content, and progressive enhancement (although SEO is more important to me). If I used `render()` as it works today, my site would still be unreadable without Javascript.

It would be great if there could be an option to just return a DOM element or HTML string from `render()`, without the wrapping `<script>` tags. This is common for other SSR implementations like React's (see first paragraph of http://redux.js.org/docs/recipes/ServerRendering.html).

**Comment by treshugart** [comment]
If you render, your content will still be accessible by crawlers even without JS. The `<script />` tags do not wrap the content, so you'll be fine.

However, there is an experimental option called `rehydrate` that you can set to `false`, either by way of passing `--no-render` to the CLI tool, or by calling `render(node, { rehydrate: false })`.

If you don't rehydrate, class names will be scoped but other selectors won't be. We have plans to extend `:host` and `::slotted` to things that will work in this mode.

**Comment by mortenson** [comment]
@treshugart Oh crazy! I was trying to read through the example at https://github.com/skatejs/ssr#usage but missed the closing `script` tags. I'll go ahead and close this out, thanks for the quick reply.
