### ISSUE TITLE
HTMLElement is undefined - Polymer

### ISSUE THREAD

**Issue by yorrd** [skatejs/ssr#27]
Hi,

background: I'm trying to get SSR with Polymer / Meteor to work. The Meteor part is sorted, now I "only" need to get your amazing skatejs/ssr to play along nicely.

At the moment, I'm using this code on my server side in Meteor:
```

class Hello extends HTMLElement {
    connectedCallback() {
        const shadowRoot = this.attachShadow({ mode: 'open' });
        shadowRoot.innerHTML = '<span>Hello!</span>';
    }
}
render(new Hello(), true).then(console.log);
```
... plus some Meteor stuff.

Now I'm getting `HTMLElement is not defined`. I'm guessing I overlooked something in your readme, but the example you gave did it in a similar way. Do I have to load a [shim](https://www.npmjs.com/package/html-element) for `HTMLElement`?

Thanks for your help

**Comment by bedeoverend** [comment]
@yorrd are you including `require('@skatejs/ssr/register');` at the top of the script? That should make HTMLElement available.

Also you might struggle to get Polymer to work with this library - I've tried a few times before and have run into issues. For starters, you'll need to be using Polymer 3, as HTML Imports which is used by Polymer 2/1 isn't supported by this lib, and on top of that there're a few things `@skatejs/ssr/register` doesn't support e.g. I don't think we've implemented HTMLTemplateElement  yet. Having said that - would love to hear how you go with it!

**Comment by treshugart** [comment]
> I don't think we've implemented HTMLTemplateElement yet.

Yeah, this is correct. I've been refactoring the codebase to better accept subclasses like this. It should land soon.

I'm also interested in your mileage. I haven't had a use case for Polymer (obv, right) but would like to be compat if it's reasonable.

**Comment by yorrd** [comment]
@bedeoverend 
@treshugart 

Alright, I'm really glad you're looking positively on the Polymer "cooperation", was kinda afraid I'd just get a "not interested". 

Now for the state of things:

1. I've managed to use the library with a test component now, thanks, I just missed that line
2. I've been working with the Meteor / Polymer combination in different variations for 1-2 years now. It has been really exciting for me because we get stuff done really quick for customers. Now I'm trying to integrate all of this even further and with redux. Redux had me think about SSR, because honestly, first meaningful paints are reaaaalllly slow in our base project, I think mostly because of the interpreting / rendering cost. 
3. At the moment, skatejs/ssr is (as far as I know) the only viable solution for WebComponents SSR (apart from completely going crazy with a chromium instance on the server). Honestly, I don't know skatejs very well at all yet. The current plan is to wait for Polymer 3 / lit-html and then compare our choices. Until then, I need a solution for SSR though.
4. Status with Polymer: I'm waiting for an update from the Meteor / Polymer integration concerning babel. If this doesn't get moving, I'll create a test project with only Polymer in the next days

All this means, for our running operations, the skatejs/ssr / polymer thing would be really amazing and I'm willing to put in a lot of work to make this work if you guys are in on it. 

I'll keep you posted. Excited for where this could be going!

**Comment by yorrd** [comment]
Alright, I'm back. Progress:

My other stuff is playing along nicely now. Unfortunately, Polymer doesn't feel well on the server environment yet, more specifically, webcomponentsjs.

I have already fixed issues concerning the window object and the document object by adding the `window` package from npm. Here's some code which needs to run globally:

```
// for the Element object
require('@skatejs/ssr/register');
// for the window and document object and infrastructure on node
const Window = require('window');

window = new Window();
document = window.document;

require('./node_modules/@webcomponents/webcomponentsjs/webcomponents-lite.js');
```

Then I stumbled on the issue that `Element` isn't defined. My conclusion: I'm missing `webcomponentsjs`. Requiring `webcomponents-lite.js` (basically all you can get) or either one of the lesser-featured versions fixes the `Element`-missing-issue, but results in this error:

```
TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
     at convert (<clip>/node_modules/jsdom/lib/jsdom/living/generated/Event.js:307:11)
     at Document.dispatchEvent (<clip>/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:141:13)
     at <clip>/node_modules/@webcomponents/webcomponentsjs/webcomponents-lite.js:23:307
     at <clip>/node_modules/@webcomponents/webcomponentsjs/webcomponents-lite.js:11:314
     at I (<clip>/node_modules/@webcomponents/webcomponentsjs/webcomponents-lite.js:11:69)
     at <clip>/node_modules/@webcomponents/webcomponentsjs/webcomponents-lite.js:11:291
     at b (<clip>/node_modules/@webcomponents/webcomponentsjs/webcomponents-lite.js:11:200)
     at z (<clip>/node_modules/@webcomponents/webcomponentsjs/webcomponents-lite.js:11:253)
     at A (<clip>/node_modules/@webcomponents/webcomponentsjs/webcomponents-lite.js:11:271)
     at window.HTMLImports (<clip>/node_modules/@webcomponents/webcomponentsjs/webcomponents-lite.js:23:278)
```

1. is there an alternative to webcomponentsjs? As far as I know, it should only be a polyfill. Does the Element object currently need to be polyfilled?
2. do you have a clue what I'm missing here? Could there be any further parts of the browser API which node is missing in this case?

Looking forward to hearing from you :)

**Comment by treshugart** [comment]
I'm closing this because I've carried it over to the monorepo in https://github.com/skatejs/skatejs/issues/1263. We can continue the discussion there. I've also linked to this.
