### ISSUE TITLE
Usage docs incorrect as of v0.16.0

### ISSUE THREAD

**Issue by bedeoverend** [skatejs/ssr#28]
Looks like in v0.16.0 the `render` function now takes a resolver, rather than a node, so the [usage example](https://github.com/skatejs/ssr#usage) now seems to be broken - does this just need to update the usage docs? Happy to patch

**Comment by treshugart** [comment]
Yeah it does. I'm moving over the docs to the monorepo now so I'll just do it along with that! Thanks for the report.

**Comment by treshugart** [comment]
Ah wait, I actually patched that recently. I'll push a release fixing it.
