### ISSUE TITLE
Slotting with Jest

### ISSUE THREAD

**Issue by mattdsteele** [skatejs/ssr#3]
Using current ssr, val, bore, jest. I'm experimenting with slotting behavior:

```javascript
const { h } = require('@skatejs/val');
const { mount } = require('@skatejs/bore');

class Hello extends HTMLElement {
  connectedCallback () {
    if (!this.shadowRoot) {
        const shadowRoot = this.attachShadow({ mode: 'open' });
        shadowRoot.innerHTML = '<span>Hello, <x-yell><slot>Default (Hello)</slot></x-yell>!</span>';
    }
  }
}
class Yell extends HTMLElement {
  connectedCallback () {
    Promise.resolve().then(() => {
      if (!this.shadowRoot) {
        const shadowRoot = this.attachShadow({ mode: 'open' });
        shadowRoot.innerHTML = '<strong><slot>Default (Yell)</slot></strong>';
      }
    });
  }
}
customElements.define('x-hello', Hello);
customElements.define('x-yell', Yell);

describe('vanilla CE', () => {
    it('does not render elements properly', () => {
        const yell = mount(<Yell>World</Yell>).wait((yell) => {
            const hello = mount(<Hello>World</Hello>);
            console.log(hello.node.shadowRoot.innerHTML);
            console.log(yell.node.shadowRoot.innerHTML);
        });
    });
});
```

For hello node, outputs: ` <span>Hello, <x-yell><slot>Default (Hello)</slot></x-yell>!</span>`
For yell node, outputs `<strong><slot>Default (Yell)</slot></strong>`

I'd have expected to have gotten an element with my content slotted in, but I'm not sure a great way to actually make that work. Do elements need to be rehydrated when running in Jest? Should this behavior live in jsdom?

**Comment by treshugart** [comment]
When you get the `innerHTML` of a shadow root, you don't get the composed tree, you get exactly what you rendered to it, so the output you're seeing is spec compliant.

**Comment by mattdsteele** [comment]
Ah, that makes sense. I was hoping I could dig around in the element and test out how it looks after it's been composed, but maybe that's an anti-pattern. Probably just need to expect the browser to do the right thing.

Thanks for the info!

**Comment by treshugart** [comment]
Yeah, I'd expect the browser to do the right thing here. If you need to get slotted content, you select the slot node and call `assignedNodes()`. We don't polyfill this, though, for the reason you mentioned. If there's a need, I'm not opposed to it.
